// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DrMofrad.Api.Models.TryEFTools
{
    public partial class ContactU
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Cell { get; set; }
        public string Message { get; set; }
        public DateTime? Date { get; set; }
        public bool? IsReaded { get; set; }
    }
}